"""modify models

Revision ID: acd1f9b30459
Revises: 7eaf93ebd4bf
Create Date: 2025-05-26 17:01:44.561591

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "acd1f9b30459"
down_revision: Union[str, None] = "7eaf93ebd4bf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    ALTER TABLE movie_showtimes
    ALTER COLUMN showtime TYPE TIME WITHOUT TIME ZONE
    USING showtime::time
""")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("movie_showtimes", "showtime", existing_type=sa.Time(), type_=sa.VARCHAR(), existing_nullable=False)
    # ### end Alembic commands ###
