"""add capacity to cinema room table

Revision ID: fd61b8ae9c76
Revises: 5b80b4c2f70e
Create Date: 2025-05-26 11:37:13.679561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd61b8ae9c76'
down_revision: Union[str, None] = '5b80b4c2f70e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cinema_rooms', sa.Column('capacity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cinema_rooms', 'capacity')
    # ### end Alembic commands ###
